### ISSUE TITLE
Lab Instructions Unclear

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/namespaced-routes-lab#19]
I feel like I cheated the solution to get the tests to pass. So I looked at the solution to compare my code and I didn't really see any solution/change to original code. I am very confused as to what exactly I should be learning from this lab.

**Comment by gb23** [comment]
I second that.  This lab is terribly unclear

**Comment by joshuabamboo** [comment]
This sentiment has been expressed to countless times when pair programming with students

**Comment by RochelLevi** [comment]
Can I jump on this train?

**Comment by drakeltheryuujin** [comment]
I don't have much information to go on as these comments are fairly old. This lab has had some updates made since, so I'm going to close it for now. If you can provide further detail about what could be done to make this lab more clear, feel free to re-open this issue and we can prioritize updates for another release of this curriculum.

As always, thanks for contributing! 💙
